### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by MonoAdrian23** [JaxkDev/Vehicles#10]
Internal Server Error when you will tap a car to remove it.
Pocketmine 3.11.4
Latest Vehicles 
Sorry for my bad english.
Youre Plugin is very nice and i hope you can fix this bug please.

**Comment by DataLiontje** [comment]
There isn't anything he can do about it you come here and just say its an internal server error.

When that happens it ALWAYS shows an error in the console.
I'm sure pasting that error in here would help a lot.

Because this is like saying: Can you help me find something? But I don't know what!
