### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by UnEnanoMas** [JaxkDev/Vehicles#15]
**Describe the bug**
When i spawn a car, i drive it and when i go off of the car and i write /vehicles remove and y touch the car he kick me out of the game saying Internal server error

**To Reproduce**
1. Spawn a vehicle '...'
2. Enter in an drive a little'....'
3. Go out of the car '....'
4. Write /vehicles remove and click the car
5.Error:
Server thread/CRITICAL Error: "Call to a member function getServer() on null" (EXCEPTION) in "src/pocketmine/event/entity/EntityDamageByEntityEvent" at line 65
15.04 09:37:02 [Server] Server thread/DEBUG #0 plugins/AdminTroll-a-plugin-PocketMine-MP-_dev-31.phar/src/Swourire/AdminTroll/Troll/TrollEventWatcher(36): pocketmine\event\entity\EntityDamageByEntityEvent->getDamager()
15.04 09:37:02 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/MethodEventExecutor(42): Swourire\AdminTroll\Troll\TrollEventWatcher->onPlayerHit(object pocketmine\event\entity\EntityDamageByEntityEvent)
15.04 09:37:02 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object Swourire\AdminTroll\Troll\TrollEventWatcher, object pocketmine\event\entity\EntityDamageByEntityEvent)
15.04 09:37:02 [Server] Server thread/DEBUG #3 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent)
15.04 09:37:02 [Server] Server thread/DEBUG #4 src/pocketmine/entity/Entity(925): pocketmine\event\Event->call()
15.04 09:37:02 [Server] Server thread/DEBUG #5 src/pocketmine/Player(2570): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
15.04 09:37:02 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(150): pocketmine\Player->handleInventoryTransaction(object CortexPE\network\InventoryTransactionPacket)
15.04 09:37:02 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(178): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(object CortexPE\network\InventoryTransactionPacket)
15.04 09:37:02 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
15.04 09:37:02 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/protocol/BatchPacket(126): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object CortexPE\network\InventoryTransactionPacket)
15.04 09:37:02 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
15.04 09:37:02 [Server] Server thread/DEBUG #11 src/pocketmine/Player(3100): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
15.04 09:37:02 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
15.04 09:37:02 [Server] Server thread/DEBUG #13 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[19] 46.222.234.94 57930, object raklib\protocol\EncapsulatedPacket, integer 0)
15.04 09:37:02 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
15.04 09:37:02 [Server] Server thread/DEBUG #15 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
15.04 09:37:02 [Server] Server thread/DEBUG #16 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
15.04 09:37:02 [Server] Server thread/DEBUG #17 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
15.04 09:37:02 [Server] Server thread/DEBUG #18 src/pocketmine/Server(2146): pocketmine\snooze\SleeperHandler->sleepUntil(double 1586943422.0566)
15.04 09:37:02 [Server] Server thread/DEBUG #19 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
15.04 09:37:02 [Server] Server thread/DEBUG #20 src/pocketmine/Server(1584): pocketmine\Server->start()
15.04 09:37:02 [Server] Server thread/DEBUG #21 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
15.04 09:37:02 [Server] Server thread/DEBUG #22 src/pocketmine/PocketMine(296): pocketmine\server()
15.04 09:37:02 [Server] Server thread/DEBUG #23 (11): require(string[108] phar:///PMMP-Latest-Stable.phar/s)

**Actual Behaviour**
Crash the player

**Client (please complete the following information):**
 - OS: [Android 9.0]
 - MCPE-Version: [e.g. 1.14.30]
 - PMMP-Version: [e.g. Latest stable]
 - Plugin-Version: [e.g. 0.0.2]

Sorry for my english :c

**Comment by JaxkDev** [comment]
Other plugins are interfering, Admin Troll 
And I presume TeaSpoon from that log.

**Comment by UnEnanoMas** [comment]
I try whitout the admintroll but they dont work

Server thread/CRITICAL Error: "Call to a member function getServer() on null" (EXCEPTION) in "src/pocketmine/event/entity/EntityDamageByEntityEvent" at line 65
15.04 10:06:59 [Server] Server thread/DEBUG #0 plugins/Friends/src/event/player/PlayerDamage(19): pocketmine\event\entity\EntityDamageByEntityEvent->getDamager()
15.04 10:06:59 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/MethodEventExecutor(42): event\player\PlayerDamage->onDamage(object pocketmine\event\entity\EntityDamageByEntityEvent)
15.04 10:06:59 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object event\player\PlayerDamage, object pocketmine\event\entity\EntityDamageByEntityEvent)
15.04 10:06:59 [Server] Server thread/DEBUG #3 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent)
15.04 10:06:59 [Server] Server thread/DEBUG #4 src/pocketmine/entity/Entity(925): pocketmine\event\Event->call()
15.04 10:06:59 [Server] Server thread/DEBUG #5 src/pocketmine/Player(2570): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
15.04 10:06:59 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(150): pocketmine\Player->handleInventoryTransaction(object CortexPE\network\InventoryTransactionPacket)
15.04 10:06:59 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(178): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(object CortexPE\network\InventoryTransactionPacket)
15.04 10:06:59 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
15.04 10:06:59 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/protocol/BatchPacket(126): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object CortexPE\network\InventoryTransactionPacket)
15.04 10:06:59 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
15.04 10:06:59 [Server] Server thread/DEBUG #11 src/pocketmine/Player(3100): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
15.04 10:06:59 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
15.04 10:06:59 [Server] Server thread/DEBUG #13 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[16] 81.0.47.74 28936, object raklib\protocol\EncapsulatedPacket, integer 0)
15.04 10:06:59 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
15.04 10:06:59 [Server] Server thread/DEBUG #15 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
15.04 10:06:59 [Server] Server thread/DEBUG #16 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
15.04 10:06:59 [Server] Server thread/DEBUG #17 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
15.04 10:06:59 [Server] Server thread/DEBUG #18 src/pocketmine/Server(2146): pocketmine\snooze\SleeperHandler->sleepUntil(double 1586945219.9344)
15.04 10:06:59 [Server] Server thread/DEBUG #19 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
15.04 10:06:59 [Server] Server thread/DEBUG #20 src/pocketmine/Server(1584): pocketmine\Server->start()
15.04 10:06:59 [Server] Server thread/DEBUG #21 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
15.04 10:06:59 [Server] Server thread/DEBUG #22 src/pocketmine/PocketMine(296): pocketmine\server()
15.04 10:06:59 [Server] Server thread/DEBUG #23 (11): require(string[108] phar:///PMMP-Latest-Stable.phar/s)

**Comment by JaxkDev** [comment]
The plugin works, like I’ve said it’s other plugins interfering.

**Comment by UnEnanoMas** [comment]
Oh ok

But only its a suggestion, if u give id´s like slappers and u only need do the command /vehicle id and touch it and he say the id and u only need write /vehicles remove x was more better an dont have any problems whit any pluggins

Just only a suggestion

**Comment by JaxkDev** [comment]
/vehicle id then touching it would give the exact same problem as your experiencing now just making more issues of having to ID each vehicle and adding an extra step to remove them.
