### ISSUE TITLE
[I want you to correspond to Altay]

### ISSUE THREAD

**Issue by NekoFuwa1739** [JaxkDev/Vehicles#17]
Although Altay can use the same plugin with pmmp derived software, it does not correspond.
Correspondence of vehicle

Because it is Japanese, it is not English. I'm sorry
![Screenshot_20200520-172556_Internet](https://user-images.githubusercontent.com/62869023/82425682-d15b2b00-9ac1-11ea-9695-24cd3307382a.jpg)

**Comment by NekoFuwa1739** [comment]
![Screenshot_20200520-174841_Internet](https://user-images.githubusercontent.com/62869023/82425962-331b9500-9ac2-11ea-89cd-a04f24c25ec4.jpg)

**Comment by NekoFuwa1739** [comment]
![Screenshot_20200520-174841_Internet](https://user-images.githubusercontent.com/62869023/82426128-6c540500-9ac2-11ea-9525-513248b5af3a.jpg)

**Comment by JaxkDev** [comment]
I will not be spending time adding compatibility to a unstable software.
