### ISSUE TITLE
[Bug] 'action.hint.exit.player' popup

### ISSUE THREAD

**Issue by LegoFan48737** [JaxkDev/Vehicles#2]
When you enter a Car, `action.hint.exit.player` shows up above the `Sneak/Jump to leave the vehicle`.
![Screenshot_20191004-152005](https://user-images.githubusercontent.com/47439649/66234065-bebeed80-e6ba-11e9-82f7-98da335108fd.png)
Other than this, the only thing I've noticed is that the car cant go up slabs, which is a feature I think should be added so that people can drive on bridges, up ramps, etc. I understand there could be an issue with using a car to literally drive up a wall, but if you only allow Slabs/Half Blocks, it couldn't be that big of an issue.

On a different note, will a guide for how to make our own vehicles be added in a future addition?

**Comment by JaxkDev** [comment]
Ive noticed it since the start of driving however i believe thats client sided, but cant remember what i said it was.
I will get back to you about the pop up, as for the slabs #1 
The guide will need a lot of work and im stretched for time i will do it asap.

**Comment by JaxkDev** [comment]
Ok so, when your 'driving' you get linked to the vehicle entity and the client does something and i think it sends back that hint but i cant find it being sent/received.
(SetActorLinkPacket)

**Comment by JaxkDev** [comment]
Ok so when the client links you to the vehicle it sends that hint (client sided) reason it says .player is because of the method i used to get the designs onto the entity.

**Comment by thebigsmileXD** [comment]
I think what could be done is that you send a popup or subtitle (something that uses the action bar as text display) to "overwrite" it.
And yes, sadly this is client sided, the only "default" way to change the message is to add a resource pack containing translations and the action.hint.exit.player message.
https://bugs.mojang.com/browse/MCPE-12433

**Comment by JaxkDev** [comment]
Thank you @thebigsmileXD I originally wanted it to overwrite it with the Sneak/Jump but the popup didnt cover it, just changed it to hint now and it works a charm.
@LegoFan48737 untranslated message is now gone.
