### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by xDanub** [JaxkDev/Vehicles#22]
I would suggest a way to pick up the cars and put them in your inventory. This way players cant steal your car and you don't have to implement a complicated lock system.

**Comment by xDanub** [comment]
A good way to do this is maybe have a `/vehicles container` or something along the lines of that as a command and you can hit a car with it to pick the car up and right click the ground to set the car back down on the ground.

**Comment by xDanub** [comment]
Awesome plugin btw :D

**Comment by JaxkDev** [comment]
In terms of complication it would be more complicated to implement this than a lock system and this is also very specific so i probably wont end up adding this however a plugin is more then capable of adding this behaviour.

**Comment by JaxkDev** [comment]
Link to #3 (Reminder add public event for damage/destroyed)
