### ISSUE TITLE
[BUG] Players without a perms can drive

### ISSUE THREAD

**Issue by UnEnanoMas** [JaxkDev/Vehicles#23]
**Describe the bug**
If you cancel the permission to ride the cars, and put OP or False, the player can ride and drive the car

**To Reproduce**
1. Change plugin permissions yml to OP or False
2. Restart the server
3. Spawning a car and get the OP off
4. Click on the car, and you can ride and drive it
**Expected behaviour**
That he got an error like: You can't get in the car because you don't have enough permissions

**Actual Behaviour**
That the player can get on and go with the car

**Screenshots**
![image](https://user-images.githubusercontent.com/63286108/100240407-d3032100-2f32-11eb-8bd1-116c92221c44.png)

**Client (please complete the following information):**
 - OS: Windows 10, Android 10
 - MCPE-Version: 1.16.100
 - PMMP-Version: 3.16.0
 - Plugin-Version: Latest version

**Server Log**
Nothing crash

**Comment by JaxkDev** [comment]
Changing the plugin.yml may cause side effects, im not sure how pmmp handles permission changes however they are set to True so every player can be the driver/passenger unless the permission is removed (via PurePerms etc).
I will try to reproduce using PurePerms but if it works as designed then i assume messing with the plugin manifest is the cause.

**Comment by UnEnanoMas** [comment]
Is that I remove the permissions to the players, changing the true of driving and riding as a passenger to false, but it did not work

**Comment by JaxkDev** [comment]
So spent quite some time digging into this, changing the default permission to OP means it works as expected.
The only problem with having true permissions is that no plugin currently removes them from specific people meaning its impossible to remove the permission without a custom plugin.

Could end up forcing all permissions to OP, and then servers can set them to true for players on demand with their own permission manager.

**Comment by UnEnanoMas** [comment]
The permission still doesn't work for me

**Comment by JaxkDev** [comment]
I have just tried it on a blank server so i cannot help if its not reproducible, by changing default to OP i mean in the plugin manifest which means running source/modified so i cant help with that either.

**Comment by UnEnanoMas** [comment]
So there is something interfering with the permissions?

**Comment by JaxkDev** [comment]
Well i don't know in your case, its very vague on what i can figure out.
You've mentioned removing the permission which I've been looking into, and i don't think its actually possible without a custom plugin, so not sure what you've been doing.
But as mentioned above the only way to remove it is by a custom plugin (i think), Or changing plugin manifest but that means building modified source and that's not something i support or help with.
