### ISSUE TITLE
[BUG] Crash at 1.16.220

### ISSUE THREAD

**Issue by UnEnanoMas** [JaxkDev/Vehicles#28]
**Describe the bug**
Crashes the game when you click

**To Reproduce**
1. Click any block
2.  You got it

**Expected behaviour**
That nothing will happen when clicking on any block

**Actual Behaviour**
Well, what crashes when you click somewhere

**Screenshots**

**Client (please complete the following information):**
 - OS: Android 11
 - MCPE-Version: 1.16.220
 - PMMP-Version: 3.19.0
 - Plugin-Version: Dev 24

**Server Log**
[Crash Vehicles.txt](https://github.com/JaxkDev/Vehicles/files/6278083/Crash.Vehicles.txt)

**Comment by JaxkDev** [comment]
No support for modified source code.
