### ISSUE TITLE
Car not jump

### ISSUE THREAD

**Issue by korarit** [JaxkDev/Vehicles#30]
How to car jump after block in font is Higher car 
![image](https://user-images.githubusercontent.com/34512081/119769963-b47fe180-bee5-11eb-816a-89f522913f3e.png)

**Comment by korarit** [comment]
My BBox and gravity

"BBox": [0,4,0,4.5,1,3.5],
  "gravity": 2,

**Comment by JaxkDev** [comment]
You can't, unless you heavily modify the vehicle internal code.

Planned feature, not yet implemented.
