### ISSUE TITLE
PoliceCar not spawning 

### ISSUE THREAD

**Issue by daksh100sharma** [JaxkDev/Vehicles#38]
I did the same as u wrote in github page. but still when i spawn PoliceCar idk what Basiccar always spawn..
[Vehicles.zip](https://github.com/JaxkDev/Vehicles/files/7780721/Vehicles.zip)
.

**Comment by Rover17-Dev** [comment]
Hello 
In the vehicles folder in PoliceCar.json file
You have forgot to change the design name from  ` "design": "BasicCar",` to "`design": "PoliceCar",`

**Comment by Rover17-Dev** [comment]
And the texture size must be 128x128 or 64x64 it is written on the wiki

**Comment by JaxkDev** [comment]
Yeah your texture of 256x256 is too large it needs to be 128x128 max (https://github.com/JaxkDev/Vehicles/wiki/Creation_Vehicles_2#stage-2---blockbench-setup)

also your geometry i cant tell if they are the *exact* but they need different identifiers if not.
(This is a design flaw you should be able to register different designs for the same geometry model but different vehicle name)
