### ISSUE TITLE
[BUG] png formats not accepting?

### ISSUE THREAD

**Issue by SuperAdam47** [JaxkDev/Vehicles#4]
Png formats now not accepting?

[Server thread/WARNING]: [Vehicles] 'police' has not got valid skin data, and so it has been disabled.

![police](https://user-images.githubusercontent.com/16169771/66254097-58010900-e77a-11e9-9a90-c7aad01a3125.png)

**Comment by JaxkDev** [comment]
The plugin fully supports png/json format, that is a validation issue and by the looks of it its because of that size.....

**Comment by JaxkDev** [comment]
allowed sizes/resolution:  https://github.com/pmmp/PocketMine-MP/blob/f0539f48983a3961290f2a4b9828586cc11b0008/src/pocketmine/entity/Skin.php#L33

**Comment by SuperAdam47** [comment]
now acceptted png but why not loaded

**Comment by SuperAdam47** [comment]
geometry
{
	"format_version": "1.12.0",
	"minecraft:geometry": [
		{
			"description": {
				"identifier": "geometry.police",
				"texture_width": 128,
				"texture_height": 128,
				"visible_bounds_width": 17,
				"visible_bounds_height": 4,
				"visible_bounds_offset": [0, 2, 0]
			},
			"bones": [
				{
					"name": "bone",
					"pivot": [-20, 0, 0],
					"rotation": [0, 40, 0],
					"cubes": [
						{"origin": [-5.56062, 16, -41.30222], "size": [17.7, 9, 1], "uv": [580.875, 1096.875]}
					]
				},
				{
					"name": "bone21",
					"parent": "bone",
					"pivot": [-20, 0, 0],
					"rotation": [0, 5, 0],
					"cubes": [
						{"origin": [-2.34466, 3, -44.35534], "size": [16.7, 14, 8], "uv": [714.875, 1112]}
					]
				},
				{
					"name": "bone12",
					"parent": "bone",
					"pivot": [-20, 0, 0],
					"rotation": [-75, 0, 0],
					"cubes": [
						{"origin": [-3.56062, -32.37364, -35.6989], "size": [14.7, 8.5, 1.5], "uv": [0, 99]},
						{"origin": [-5.56062, -32.37364, -35.6989], "size": [4.7, 2.5, 1.5], "uv": [0, 0]}
					]
				},
				{
					"name": "bone13",
					"parent": "bone",
					"pivot": [-20, 0, 0],
					"rotation": [-75, 0, 0],
					"cubes": [
						{"origin": [-5.56062, -33.37364, -35.43631], "size": [17.7, 1, 1], "uv": [0, 0]}
					]
				},
				{
					"name": "bone14",
					"parent": "bone",
					"pivot": [-20, 0, 0],
					"rotation": [-75, 0, 0],
					"cubes": [
						{"origin": [-5.56062, -33.37364, -35.43631], "size": [17.7, 1, 1], "uv": [0, 0]}
					]
				},
				{
					"name": "bone2",
					"parent": "bone",
					"pivot": [-20, 0, 0],
					"rotation": [0, 0, 15],
					"cubes": [
						{"origin": [-12.57921, 19.34125, -41.30222], "size": [2, 8.4, 1], "uv": [688, 1129]}
					]
				},
				{
					"name": "bone3",
					"pivot": [32, 0, 12],
					"rotation": [0, -40, 0],
					"cubes": [
						{"origin": [-17.83938, 16, -29.30222], "size": [17.7, 9, 1], "uv": [780, 1134.875]},
						{"origin": [-17.83938, -33.37364, -23.43631], "size": [18.7, 7, 1], "pivot": [32, 0, 12], "rotation": [-75, 0, 0], "uv": [0, 0]},
						{"origin": [-17.83938, -26.37364, -23.43631], "size": [9.7, 3, 1], "pivot": [32, 0, 12], "rotation": [-75, 0, 0], "uv": [0, 0]}
					]
				},
				{
					"name": "bone22",
					"parent": "bone3",
					"pivot": [32, 0, 12],
					"rotation": [0, -7, 0],
					"cubes": [
						{"origin": [-23.26769, 3, -28.09992], "size": [18.7, 14, 8], "uv": [769, 1091]}
					]
				},
				{
					"name": "bone4",
					"parent": "bone3",
					"pivot": [32, 0, 12],
					"rotation": [0, 0, -15],
					"cubes": [
						{"origin": [5.57921, 24.54125, -29.30222], "size": [2, 7.8, 1.3], "uv": [688, 1129]}
					]
				},
				{
					"name": "bone5",
					"pivot": [30, 0, 9],
					"cubes": [
						{"origin": [-23, 16, -54], "size": [45, 1, 3], "uv": [0, 0]},
						{"origin": [-26, 2, -56], "size": [49, 14, 7], "uv": [548, 1122.875]},
						{"origin": [-22, 7, -64], "size": [4, 23, 3], "uv": [791, 640]},
						{"origin": [-23, 20, -66], "size": [6, 6, 2], "uv": [1860, 322]},
						{"origin": [11, 20, -66], "size": [6, 6, 2], "uv": [1856, 286.875]},
						{"origin": [12, 7, -64], "size": [4, 23, 3], "uv": [791, 640]},
						{"origin": [-18, 21, -64], "size": [30, 4, 3], "uv": [791, 640]},
						{"origin": [-18, 11, -64], "size": [30, 4, 3], "uv": [791, 640]},
						{"origin": [-22, 15, -51], "size": [42, 10, 2], "uv": [0, 1790.875]},
						{"origin": [-22, 19.5, -52], "size": [42, 3, 3], "uv": [680, 1247]},
						{"origin": [-2, 22, -52], "size": [3, 5, 3], "uv": [575, 1199]},
						{"origin": [1, 22.5, -52], "size": [1, 4, 3], "uv": [0, 1137]},
						{"origin": [-3, 18, -52], "size": [1, 1, 3], "uv": [0, 1137]},
						{"origin": [1, 18, -52], "size": [1, 1, 3], "uv": [0, 1137]},
						{"origin": [-3, 22.5, -52], "size": [1, 5, 3], "uv": [0, 1137]},
						{"origin": [-20, 22.5, -52], "size": [17, 0.5, 3], "uv": [0, 1137]},
						{"origin": [2, 22.5, -52], "size": [17, 0.5, 3], "uv": [0, 1137]},
						{"origin": [1, 19, -52], "size": [18, 0.5, 3], "uv": [0, 1137]},
						{"origin": [-20, 19, -52], "size": [18, 0.5, 3], "uv": [0, 1137]},
						{"origin": [-2, 16, -52], "size": [3, 4, 3], "uv": [608.875, 1180]},
						{"origin": [-21, 16, -53], "size": [42, 2, 3], "uv": [0, 1294]},
						{"origin": [-21, 16, -52], "size": [2, 4, 3], "uv": [161, 688]}
					]
				},
				{
					"name": "bone48",
					"parent": "bone5",
					"pivot": [0, 0, 0],
					"rotation": [-35, 0, 0],
					"cubes": [
						{"origin": [12, -31, -56], "size": [4, 4, 10], "uv": [702, 830]},
						{"origin": [-22, -31, -56], "size": [4, 4, 10], "uv": [702, 830]}
					]
				},
				{
					"name": "bone8",
					"parent": "bone5",
					"pivot": [30, 0, 9],
					"rotation": [0, 0, -5.5],
					"cubes": [
						{"origin": [-19.65816, 28.93554, -54], "size": [22, 1, 3], "uv": [0, 0]},
						{"origin": [-17.65816, 27.93554, -53], "size": [20, 1, 2], "uv": [75, 1161.875]}
					]
				},
				{
					"name": "bone10",
					"parent": "bone8",
					"pivot": [30, 0, 9],
					"rotation": [30, 0, 0],
					"cubes": [
						{"origin": [-10.65816, 55.06854, -29.33349], "size": [13, 2, 10], "uv": [1763, 799]},
						{"origin": [-19.1, 55.06854, -29.33349], "size": [8.5, 2, 10], "uv": [0, 0]},
						{"origin": [-19.65816, 54.06854, -22.33349], "size": [22, 2, 3], "uv": [0, 0]}
					]
				},
				{
					"name": "bone9",
					"parent": "bone5",
					"pivot": [30, 0, 9],
					"rotation": [0, 0, 5],
					"cubes": [
						{"origin": [-3.22018, 23.44673, -54], "size": [22, 1, 3], "uv": [0, 0]},
						{"origin": [-3.22018, 22.44673, -53], "size": [20, 1, 2], "uv": [0, 1408.875]}
					]
				},
				{
					"name": "bone11",
					"parent": "bone9",
					"pivot": [30, 0, 9],
					"rotation": [30, 0, 0],
					"cubes": [
						{"origin": [-3.22018, 48.07822, -31.32791], "size": [14, 4, 9], "uv": [1771.875, 738]},
						{"origin": [10.77982, 48.07822, -31.32791], "size": [8, 4, 9], "uv": [0, 0]}
					]
				},
				{
					"name": "bone6",
					"parent": "bone5",
					"pivot": [30, 0, 9],
					"rotation": [0, 0, 10],
					"cubes": [
						{"origin": [-25.43108, 6.78731, -54], "size": [2, 9, 3], "uv": [0, 0]},
						{"origin": [-23.43108, 6.78731, -53], "size": [1, 8.5, 2], "uv": [0, 1167]}
					]
				},
				{
					"name": "bone7",
					"parent": "bone5",
					"pivot": [30, 0, 9],
					"rotation": [0, 0, -10],
					"cubes": [
						{"origin": [23.43108, 17.78731, -54], "size": [2, 9, 3], "uv": [0, 0]},
						{"origin": [22.43108, 17.78731, -53], "size": [1, 9, 2], "uv": [0, 1185]}
					]
				},
				{
					"name": "bone15",
					"pivot": [30, 0, 9],
					"cubes": [
						{"origin": [-14, 27, -44], "size": [27, 5, 51], "uv": [654, 1648]},
						{"origin": [-33, 47, 33], "size": [62, 2, 42], "uv": [0, 0]},
						{"origin": [-33, 49, 51], "size": [62, 5, 14], "uv": [1763, 101]},
						{"origin": [-31, 46, 33], "size": [58, 1, 42], "uv": [1268, 88]},
						{"origin": [-10, 31.2, -44], "size": [19, 1, 9], "uv": [599, 1374.875]},
						{"origin": [-2, 31.2, -35], "size": [3, 1, 43], "uv": [703, 1270]},
						{"origin": [-37, 7, -40], "size": [8, 19, 9], "uv": [0, 0]},
						{"origin": [-39, 3, -44], "size": [4, 14, 13], "uv": [0, 0]},
						{"origin": [33, 3, -42], "size": [4, 14, 11], "uv": [0, 0]},
						{"origin": [27.1, 7, -39.5], "size": [8, 19, 9], "uv": [0, 0]},
						{"origin": [-37, 22, -31], "size": [3, 4, 38], "uv": [0, 0]},
						{"origin": [32, 22, -31], "size": [3, 4, 38], "uv": [0, 0]},
						{"origin": [-37, 3, -12], "size": [72, 19, 19], "uv": [0, 57]},
						{"origin": [-35, 3, -7], "size": [67, 19, 19], "uv": [1304, 147]},
						{"origin": [-37, 3, 7], "size": [2, 23, 99], "uv": [1620, 1368]},
						{"origin": [-35, 3, 92], "size": [3, 23, 14], "uv": [0, 0]},
						{"origin": [-37, 20, 104], "size": [4, 6, 9], "uv": [0, 0]},
						{"origin": [-33, 26, 94], "size": [9, 9, 4], "uv": [0, 0]},
						{"origin": [20, 25, 94], "size": [9, 10, 4], "uv": [0, 0]},
						{"origin": [29, 20, 104], "size": [6, 6, 9], "uv": [0, 0]},
						{"origin": [29, 20, 92], "size": [6, 6, 12], "uv": [0, 0]},
						{"origin": [33, 3, 7], "size": [2, 23, 99], "uv": [1613, 1232]},
						{"origin": [34, 25, 4], "size": [8, 2, 2], "uv": [826, 671]},
						{"origin": [-44, 25, 4], "size": [8, 2, 2], "uv": [826, 671]},
						{"origin": [42, 25, 3], "size": [8, 6, 3], "uv": [1047, 1334]},
						{"origin": [-52, 25, 3], "size": [8, 6, 3], "uv": [1047, 1334]},
						{"origin": [35, 5, 9], "size": [0.1, 1, 85], "uv": [699, 0]},
						{"origin": [-37.1, 5, 9], "size": [0.1, 1, 85], "uv": [699, 0]},
						{"origin": [35, 19, 45], "size": [0.1, 2, 5], "uv": [699, 0]},
						{"origin": [-37.1, 19, 45], "size": [0.1, 2, 5], "uv": [699, 0]},
						{"origin": [35, 19, 90], "size": [0.1, 2, 5], "uv": [699, 0]},
						{"origin": [-37.1, 19, 90], "size": [0.1, 2, 5], "uv": [699, 0]},
						{"origin": [35, 25, 7], "size": [0.1, 1, 98], "uv": [699, 0]},
						{"origin": [-37.1, 25, 7], "size": [0.1, 1, 98], "uv": [761, 37.875]},
						{"origin": [35, 22, 104], "size": [0.1, 3, 1], "uv": [699, 0]},
						{"origin": [-37.1, 22, 104], "size": [0.1, 3, 1], "uv": [699, 0]},
						{"origin": [35, 21, 98], "size": [0.1, 1, 9], "uv": [699, 0]},
						{"origin": [-37.1, 21, 98], "size": [0.1, 1, 9], "uv": [699, 0]},
						{"origin": [-37, 3, 125], "size": [72, 23, 10], "uv": [0, 0]},
						{"origin": [35, 3, 125], "size": [0.1, 4, 11], "uv": [837, 803.875]},
						{"origin": [35, 3, 125], "size": [0.1, 4, 7], "uv": [837, 803.875]},
						{"origin": [-37.1, 3, 125], "size": [0.1, 4, 11], "uv": [837, 803.875]},
						{"origin": [-27, 28, 127], "size": [52, 2, 9], "uv": [0, 0]},
						{"origin": [22, 26, 127], "size": [3, 2, 9], "uv": [0, 0]},
						{"origin": [-28, 26, 127], "size": [3, 2, 9], "uv": [0, 0]},
						{"origin": [-37, 3, 135], "size": [72, 23, 1], "uv": [923, 1150.875]},
						{"origin": [-37, 20, 113], "size": [72, 6, 12], "uv": [0, 0]},
						{"origin": [32, 3, 7], "size": [1, 23, 85], "uv": [1365.875, 28]},
						{"origin": [-35, 3, 7], "size": [1, 23, 85], "uv": [1332, 23]},
						{"origin": [-34, 15, 7], "size": [66, 11, 9], "uv": [1118, 1108]},
						{"origin": [18, 19, 16], "size": [3, 3, 4], "uv": [138, 799]},
						{"origin": [16, 19, 20], "size": [7, 5, 1], "uv": [1374.875, 1128]},
						{"origin": [23, 20, 20], "size": [1, 4, 1], "uv": [1270, 0]},
						{"origin": [15, 20, 20], "size": [1, 4, 1], "uv": [1365.875, 118]},
						{"origin": [17, 18, 20], "size": [5, 1, 1], "uv": [1522.875, 14]},
						{"origin": [15, 17, 20], "size": [9, 1, 1], "uv": [285, 642]},
						{"origin": [15, 25, 20], "size": [9, 1, 1], "uv": [71, 633]},
						{"origin": [24, 18, 20], "size": [1, 7, 1], "uv": [285, 752]},
						{"origin": [14, 18, 20], "size": [1, 7, 1], "uv": [228, 790]},
						{"origin": [-13, 3, 7], "size": [11, 12, 9], "uv": [1185, 1132]},
						{"origin": [-10, 4, 16], "size": [11, 4, 35], "uv": [1304, 1128]},
						{"origin": [-5, 8, 28], "size": [1, 4, 1], "uv": [1480, 1123]},
						{"origin": [-6, 12, 27], "size": [3, 2, 3], "uv": [771, 780]},
						{"origin": [-35, 3, 7], "size": [67, 1, 68], "uv": [1327, 80]},
						{"origin": [-35, 3, 41], "size": [67, 1, 63], "uv": [1332, 90]},
						{"origin": [-32, 4, 18], "size": [19, 7, 29], "uv": [1218, 1185]},
						{"origin": [-32, 30, 58], "size": [19, 12, 8], "uv": [1218, 1278]},
						{"origin": [11, 30, 58], "size": [19, 12, 8], "uv": [1218, 1278]},
						{"origin": [-33, 4, 68], "size": [64, 7, 24], "uv": [1213, 1332]},
						{"origin": [-33, 11, 87], "size": [64, 22, 5], "uv": [1213, 1399]},
						{"origin": [11, 4, 18], "size": [19, 7, 29], "uv": [1218, 1185]},
						{"origin": [-35, 3, 75], "size": [67, 1, 20], "uv": [1451, 84.875]},
						{"origin": [-32, 4, 99], "size": [61, 22, 5], "uv": [1494, 0]},
						{"origin": [-33, 20, 92], "size": [62, 6, 21], "uv": [1213, 0]},
						{"origin": [-34, 22, -12], "size": [67, 3, 19], "uv": [0, 0]},
						{"origin": [-21, 24, -12], "size": [40, 3, 19], "uv": [0, 0]},
						{"origin": [35, 3, -12.5], "size": [2, 14, 2], "uv": [0, 0]},
						{"origin": [35, 3, 102.5], "size": [2, 9, 3], "uv": [0, 0]},
						{"origin": [-39, 3, 102.5], "size": [2, 9, 3], "uv": [147, 190]},
						{"origin": [35, 3, 125], "size": [2, 11, 3], "uv": [0, 0]},
						{"origin": [-39, 3, 125], "size": [2, 11, 3], "uv": [0, 157]},
						{"origin": [-39, 3, -11.5], "size": [2, 14, 2], "uv": [295, 176]},
						{"origin": [35, 20, -31], "size": [2, 2, 19], "uv": [0, 0]},
						{"origin": [35, 20, 105], "size": [2, 3, 20], "uv": [0, 0]},
						{"origin": [-39, 20, 105], "size": [2, 3, 20], "uv": [176, 195]},
						{"origin": [29, 6, -41], "size": [1, 1, 1], "uv": [0, 0]}
					]
				},
				{
					"name": "bone45",
					"parent": "bone15",
					"pivot": [0, 0, 0],
					"rotation": [-5, 0, 0],
					"cubes": [
						{"origin": [35, 10, 51], "size": [0.1, 20, 2], "uv": [699, 0]},
						{"origin": [-37.1, 10, 51], "size": [0.1, 20, 2], "uv": [699, 0]}
					]
				},
				{
					"name": "bone46",
					"parent": "bone15",
					"pivot": [0, 0, 0],
					"rotation": [0, 0, 10],
					"cubes": [
						{"origin": [19, 32, 127], "size": [12, 2, 9], "uv": [0, 0]}
					]
				},
				{
					"name": "bone47",
					"parent": "bone15",
					"pivot": [0, 0, 0],
					"rotation": [0, 0, -10],
					"cubes": [
						{"origin": [-33, 32, 128], "size": [12, 2, 8], "uv": [0, 0]}
					]
				},
				{
					"name": "bone43",
					"parent": "bone15",
					"pivot": [0, 0, 0],
					"rotation": [5, 0, 0],
					"cubes": [
						{"origin": [35, 5, 9], "size": [0.1, 20, 1], "uv": [699, 0]},
						{"origin": [-37.1, 5, 9], "size": [0.1, 20, 1], "uv": [699, 0]}
					]
				},
				{
					"name": "bone44",
					"parent": "bone15",
					"pivot": [0, 0, 0],
					"rotation": [-20, 0, 0],
					"cubes": [
						{"origin": [35, 37, 85], "size": [0.1, 17, 1], "uv": [699, 0]},
						{"origin": [-37.1, 37, 85], "size": [0.1, 17, 1], "uv": [699, 0]}
					]
				},
				{
					"name": "bone32",
					"parent": "bone15",
					"pivot": [0, 70, -10],
					"rotation": [-30, 0, 0],
					"cubes": [
						{"origin": [-33, 91.73205, 72.69873], "size": [9, 2, 46], "uv": [0, 0]},
						{"origin": [-33, 85.73205, 101.69873], "size": [9, 6, 14], "uv": [0, 0]},
						{"origin": [20, 85.73205, 101.69873], "size": [9, 6, 14], "uv": [0, 0]},
						{"origin": [20, 91.73205, 72.69873], "size": [9, 2, 46], "uv": [0, 0]}
					]
				},
				{
					"name": "bone29",
					"parent": "bone15",
					"pivot": [0, 0, 0],
					"rotation": [40, 10, 0],
					"cubes": [
						{"origin": [-37.31759, 17.1832, 15.56525], "size": [3, 3, 37], "uv": [0, 0]}
					]
				},
				{
					"name": "bone30",
					"parent": "bone15",
					"pivot": [0, 0, 0],
					"rotation": [40, -10, 0],
					"cubes": [
						{"origin": [31.31759, 17.1832, 15.56525], "size": [3, 3, 37], "uv": [0, 0]}
					]
				},
				{
					"name": "bone31",
					"parent": "bone15",
					"pivot": [0, 0, 0],
					"rotation": [60, 0, 0],
					"cubes": [
						{"origin": [-32, -41.69873, 31.73205], "size": [19, 7, 29], "uv": [1218, 1232]},
						{"origin": [11, -41.69873, 31.73205], "size": [19, 7, 29], "uv": [1218, 1232]}
					]
				},
				{
					"name": "bone16",
					"parent": "bone15",
					"pivot": [30, 0, 9],
					"rotation": [0, 0, -5],
					"cubes": [
						{"origin": [-19.47707, 29.97717, -44], "size": [16, 5, 51], "uv": [0, 0]}
					]
				},
				{
					"name": "bone17",
					"parent": "bone15",
					"pivot": [30, 0, 9],
					"rotation": [0, 0, 6],
					"cubes": [
						{"origin": [1.37283, 23.96713, -44], "size": [17, 5, 51], "uv": [0, 0]}
					]
				},
				{
					"name": "bone20",
					"parent": "bone15",
					"pivot": [30, 0, 9],
					"rotation": [-15, 0, 0],
					"cubes": [
						{"origin": [33, 4.8546, -35.84921], "size": [4, 6, 2], "uv": [0, 0]},
						{"origin": [34, 35.8546, 96.15079], "size": [3, 11, 3], "uv": [0, 0]},
						{"origin": [-39, 35.8546, 96.15079], "size": [3, 11, 3], "uv": [276, 285]},
						{"origin": [-39, 4.8546, -35.84921], "size": [3, 6, 2], "uv": [0, 171]}
					]
				},
				{
					"name": "bone23",
					"parent": "bone15",
					"pivot": [-30, -3, 37],
					"rotation": [15, 0, 0],
					"cubes": [
						{"origin": [34, 27.7365, -5.74337], "size": [3, 6, 2], "uv": [0, 0]},
						{"origin": [34, -10.2635, 126.25663], "size": [3, 9, 3], "uv": [0, 0]},
						{"origin": [-39, -10.2635, 126.25663], "size": [3, 9, 3], "uv": [128, 166]},
						{"origin": [-39, 27.7365, -4.74337], "size": [3, 6, 2], "uv": [0, 52]}
					]
				},
				{
					"name": "bone24",
					"parent": "bone15",
					"pivot": [30, 0, 9],
					"cubes": [
						{"origin": [-39, 20, -31], "size": [2, 2, 20], "uv": [142, 122.875]},
						{"origin": [29, 2, -41], "size": [1, 1, 1], "uv": [0, 0]}
					]
				},
				{
					"name": "bone18",
					"parent": "bone15",
					"pivot": [30, 0, 9],
					"rotation": [0, 0, -10],
					"cubes": [
						{"origin": [-29.95811, 36.40885, -36], "size": [18, 1, 4], "uv": [0, 0]},
						{"origin": [-29.95811, 33.40885, -32], "size": [18, 4, 39], "uv": [0, 0]},
						{"origin": [-29.95811, 36.40885, -37], "size": [14, 1, 1], "uv": [0, 0]},
						{"origin": [-29.95811, 36.40885, -38], "size": [14, 1, 1], "uv": [0, 0]},
						{"origin": [-18.95811, 36.40885, -40.3], "size": [3, 1, 2.3], "uv": [0, 0]},
						{"origin": [-24.95811, 36.40885, -40.3], "size": [3, 1, 2.3], "uv": [0, 0]},
						{"origin": [-29.95811, 36.40885, -40], "size": [6, 1, 2], "uv": [0, 0]}
					]
				},
				{
					"name": "bone19",
					"parent": "bone15",
					"pivot": [70, -18, 9],
					"rotation": [0, 0, 10],
					"cubes": [
						{"origin": [7.95811, 18.40885, -36], "size": [18, 1, 4], "uv": [0, 0]},
						{"origin": [7.95811, 15.40885, -32], "size": [18, 4, 39], "uv": [0, 0]},
						{"origin": [7.95811, 18.40885, -37], "size": [18, 1, 1], "uv": [0, 0]},
						{"origin": [7.95811, 18.40885, -38], "size": [14, 1, 1], "uv": [0, 0]},
						{"origin": [12.95811, 18.40885, -40.3], "size": [6, 1, 2.3], "uv": [0, 0]},
						{"origin": [18.95811, 18.40885, -40.3], "size": [3, 1, 2.3], "uv": [0, 0]},
						{"origin": [7.95811, 18.40885, -40], "size": [6, 1, 2], "uv": [0, 0]}
					]
				},
				{
					"name": "bone25",
					"parent": "bone15",
					"pivot": [30, 0, 9],
					"rotation": [0, -5, 0],
					"cubes": [
						{"origin": [-14.35779, 31.2, -34.80973], "size": [2, 1, 42], "uv": [617.875, 1289]}
					]
				},
				{
					"name": "bone26",
					"parent": "bone15",
					"pivot": [30, 0, 9],
					"rotation": [0, 5, 0],
					"cubes": [
						{"origin": [11.35779, 31.2, -37.80973], "size": [2, 1, 42], "uv": [623, 1290]}
					]
				},
				{
					"name": "bone27",
					"parent": "bone15",
					"pivot": [30, 0, 9],
					"rotation": [0, 10, 0],
					"cubes": [
						{"origin": [-1.31759, 31.1, -41.24039], "size": [12, 1, 4], "uv": [737, 1442]}
					]
				},
				{
					"name": "bone28",
					"parent": "bone15",
					"pivot": [30, 0, 9],
					"rotation": [0, -10, 0],
					"cubes": [
						{"origin": [-10.68241, 31.1, -30.24039], "size": [12, 1, 4], "uv": [737, 1451]}
					]
				},
				{
					"name": "bone41",
					"parent": "bone15",
					"pivot": [0, 0, 0],
					"rotation": [0, 0, -18],
					"cubes": [
						{"origin": [39, 14, 52], "size": [3, 23, 7], "uv": [765.875, 780]}
					]
				},
				{
					"name": "bone42",
					"parent": "bone15",
					"pivot": [0, 0, 0],
					"rotation": [0, 0, 18],
					"cubes": [
						{"origin": [-43, 13, 51], "size": [3, 23, 7], "uv": [823, 775]}
					]
				},
				{
					"name": "llanta1",
					"pivot": [-20, -21, 0],
					"cubes": [
						{"origin": [-37.7, 0, -26], "size": [9.7, 3, 9], "uv": [920, 823]},
						{"origin": [-36.7, 3, -29], "size": [0.7, 12, 14], "uv": [1680, 1036]},
						{"origin": [-35.7, 5, -26], "size": [0.7, 8, 8], "uv": [0, 0]},
						{"origin": [-37.7, 15, -27], "size": [9.7, 3, 10], "uv": [688, 672]},
						{"origin": [-37.7, 5.5, -15.5], "size": [9.7, 7, 3], "uv": [886.875, 913.875]},
						{"origin": [-37.7, 5.5, -31.5], "size": [9.7, 7, 3], "uv": [924.875, 758]}
					]
				},
				{
					"name": "bone33",
					"parent": "llanta1",
					"pivot": [0, -21, 0],
					"rotation": [50, 0, 0],
					"cubes": [
						{"origin": [-37.7, 5.70222, 5.46062], "size": [9.7, 3, 7], "uv": [710, 898]},
						{"origin": [-37.7, 21.70222, 5.46062], "size": [9.7, 3, 7], "uv": [704, 876.875]}
					]
				},
				{
					"name": "bone34",
					"parent": "llanta1",
					"pivot": [0, -21, 0],
					"rotation": [-50, 0, 0],
					"cubes": [
						{"origin": [-37.7, -27.80222, -40.13938], "size": [9.7, 3, 7], "uv": [769, 909]},
						{"origin": [-37.7, -12.10222, -40.73938], "size": [9.7, 3, 7], "uv": [758, 752.875]}
					]
				},
				{
					"name": "llanta2",
					"pivot": [44, -21, 0],
					"cubes": [
						{"origin": [26.3, 0, -26], "size": [9.7, 3, 9], "uv": [688, 780]},
						{"origin": [34.3, 3, -29], "size": [0.7, 12, 14], "uv": [1680, 1036]},
						{"origin": [31.3, 5, -26], "size": [0.7, 8, 8], "uv": [0, 0]},
						{"origin": [26.3, 15, -27], "size": [9.7, 3, 10], "uv": [769, 714.875]},
						{"origin": [26.3, 5.5, -15.5], "size": [9.7, 7, 3], "uv": [833, 866]},
						{"origin": [26.3, 5.5, -31.5], "size": [9.7, 7, 3], "uv": [866, 774]}
					]
				},
				{
					"name": "bone35",
					"parent": "llanta2",
					"pivot": [64, -21, 0],
					"rotation": [50, 0, 0],
					"cubes": [
						{"origin": [26.3, 5.70222, 5.46062], "size": [9.7, 3, 7], "uv": [661, 817]},
						{"origin": [26.3, 21.70222, 5.46062], "size": [9.7, 3, 7], "uv": [694, 651]}
					]
				},
				{
					"name": "bone36",
					"parent": "llanta2",
					"pivot": [64, -21, 0],
					"rotation": [-50, 0, 0],
					"cubes": [
						{"origin": [26.3, -27.80222, -40.13938], "size": [9.7, 3, 7], "uv": [876.875, 903]},
						{"origin": [26.3, -12.10222, -40.73938], "size": [9.7, 3, 7], "uv": [714.875, 742]}
					]
				},
				{
					"name": "llanta3",
					"pivot": [44, -21, 138],
					"cubes": [
						{"origin": [26.3, 0, 112], "size": [9.7, 3, 9], "uv": [946, 1016]},
						{"origin": [34.3, 3, 109], "size": [0.7, 12, 14], "uv": [1680, 1036]},
						{"origin": [31.3, 5, 112], "size": [0.7, 8, 8], "uv": [0, 0]},
						{"origin": [26.3, 15, 111], "size": [9.7, 3, 10], "uv": [893, 720]},
						{"origin": [26.3, 5.5, 122.5], "size": [9.7, 7, 3], "uv": [800.875, 838.875]},
						{"origin": [26.3, 5.5, 106.5], "size": [9.7, 7, 3], "uv": [758, 930]}
					]
				},
				{
					"name": "bone37",
					"parent": "llanta3",
					"pivot": [64, -21, 138],
					"rotation": [50, 0, 0],
					"cubes": [
						{"origin": [26.3, 5.70222, 143.46062], "size": [9.7, 3, 7], "uv": [747, 634]},
						{"origin": [26.3, 21.70222, 143.46062], "size": [9.7, 3, 7], "uv": [946, 731]}
					]
				},
				{
					"name": "bone38",
					"parent": "llanta3",
					"pivot": [64, -21, 138],
					"rotation": [-50, 0, 0],
					"cubes": [
						{"origin": [26.3, -27.80222, 97.86062], "size": [9.7, 3, 7], "uv": [769, 785]},
						{"origin": [26.3, -12.10222, 97.26062], "size": [9.7, 3, 7], "uv": [817, 876.875]}
					]
				},
				{
					"name": "llanta4",
					"pivot": [-20, -21, 137],
					"cubes": [
						{"origin": [-37.7, 0, 111], "size": [9.7, 3, 9], "uv": [886.875, 871]},
						{"origin": [-36.7, 3, 108], "size": [0.7, 12, 14], "uv": [1680, 1036]},
						{"origin": [-35.7, 5, 111], "size": [0.7, 8, 8], "uv": [0, 0]},
						{"origin": [-37.7, 15, 110], "size": [9.7, 3, 10], "uv": [752.875, 780]},
						{"origin": [-37.7, 5.5, 121.5], "size": [9.7, 7, 3], "uv": [747, 710]},
						{"origin": [-37.7, 5.5, 105.5], "size": [9.7, 7, 3], "uv": [930, 936]}
					]
				},
				{
					"name": "bone39",
					"parent": "llanta4",
					"pivot": [0, -21, 137],
					"rotation": [50, 0, 0],
					"cubes": [
						{"origin": [-37.7, 5.70222, 142.46062], "size": [9.7, 3, 7], "uv": [812, 580.875]},
						{"origin": [-37.7, 21.70222, 142.46062], "size": [9.7, 3, 7], "uv": [731, 694]}
					]
				},
				{
					"name": "bone40",
					"parent": "llanta4",
					"pivot": [0, -21, 137],
					"rotation": [-50, 0, 0],
					"cubes": [
						{"origin": [-37.7, -27.80222, 96.86062], "size": [9.7, 3, 7], "uv": [850, 742]},
						{"origin": [-37.7, -12.10222, 96.26062], "size": [9.7, 3, 7], "uv": [866, 962.875]}
					]
				}
			]
		}
	]
}

**Comment by SuperAdam47** [comment]
maybe you create guide

**Comment by JaxkDev** [comment]
Names have to be specific, guide will take time as mentioned in previous issues.
