### ISSUE TITLE
[BUG] Nested permission declarations are no longer supported. Declare each permission separately.

### ISSUE THREAD

**Issue by RayanK0** [JaxkDev/Vehicles#40]
**Describe the bug**
When I put the plugin in my server, I get this error message.
Could not load plugin '/home/container/plugins/Vehicles (2).phar': Invalid plugin manifest: Invalid Plugin "permissions": Nested permission declarations are no longer supported. Declare each permission separately.

**Client (please complete the following information):**
 - OS: [IOS]
 - MCPE-Version: [e.g. 1.18.0]
 - PMMP-Version: [4.0.0]
 - Plugin-Version: [0.1.15]

**Comment by Thunder33345** [comment]
Plugin version  0.1.15 clearly does not support PMMP v4
See:
https://github.com/JaxkDev/Vehicles/blob/master/plugin.yml#L3-L4

**Comment by JaxkDev** [comment]
No support for modified releases.
