### ISSUE TITLE
Wiki file is not downloading 

### ISSUE THREAD

**Issue by rexetbandityt** [JaxkDev/Vehicles#43]
Sorry, I don’t know how to use github, so I’ll answer you in a new question or how it is ... I made a mistake when I said that the BLANK.php file is not downloaded, I meant the file that is listed in the machine creation wiki https://github.com/JaxkDev /Vehicles/wiki/Creation_Vehicles_8 it says that you need to download the file, but when I follow the link it says that the page was not found. (Sorry for my english if it's bad)

**Comment by JaxkDev** [comment]
#26
