### ISSUE TITLE
[BUG] Vehicle not move [PM4]

### ISSUE THREAD

**Issue by korarit** [JaxkDev/Vehicles#44]
Vehicle is not moving  
**Screenshots**
<img src="https://i.imgur.com/kQhOd4o.png">

**Client**
 - OS: [windown]
 - MCPE-Version: 1.18.10
 - PMMP-Version: 4.2.0
 - Plugin-Version: 1.0.0

**Server Log**
Bug is not have error log

**Comment by JaxkDev** [comment]
Invalid plugin version.

**Comment by korarit** [comment]
> Invalid plugin version.
plugin is verion 1.0.0 for pocketmine 4

**Comment by JaxkDev** [comment]
Thats still invalid because its not released.
