### ISSUE TITLE
[BUG] TITLE-HERE

### ISSUE THREAD

**Issue by Kingom1** [JaxkDev/Vehicles#50]
![Screenshot_٢٠٢٣٠٨٠٩-٢٢٥٥٢٦](https://github.com/JaxkDev/Vehicles/assets/102631520/d5b4d451-7fab-4527-8484-7d444ba071ab)

**Comment by JaxkDev** [comment]
Plugin does not work on PM4/5 and 0 support for modified versions

**Comment by Kingom1** [comment]
Works on pm5 with me

**Comment by JaxkDev** [comment]
Clearly not, but still.

Absolutely no support for modified versions of plugin and/or pmmp.
