### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by jaylac2000** [JaxkDev/Vehicles#9]
Add a pick up Truck

Holds passenger, driver, 3 people in the back

add a bus 

holds driver maybe 48 people (24 seats) 2 people per seat

make vehicles require a key so no one can steal your vehicle 

sounds funny... but add a cop car with functional lights and sirens

**Comment by jaylac2000** [comment]
make a "master key" for ops so they can drive any car that belongs to anyone

**Comment by JaxkDev** [comment]
Won’t be added into core, feel free to model them yourself and then add them.
